spring:
  datasource:
    url: jdbc:h2:~/pushmyshop;INIT=create schema if not exists pushmyshop;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE
    username: pushmyshop
    password: pushmyshop
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework: DEBUG

web:
  push:
    vapid:
      public-key: BGgM0ydbnR-04QSrQyPMC0JMqA7xF6TSQ8Wb7rtKa5PSTdOjpSmdydadrrlwuPziFhUM8DodMt_t09nDi7oFtSY
      private-key: OYi3b_J794O-PTFzaAbqX5vbXrQz5XnK7lq7tmMXErg